### ISSUE TITLE
Multi language website

### ISSUE THREAD

**Issue by Juliengoodconsulting** [ColorlibHQ/shapely#326]
Dears,
I am very happy with Shapely and doing my second website with it too.
I post my issue as i has been advised to do.
Now I am struggling with the translation of the homepage :
Main language is French
When I duplicate the page for the translation, naming it “Homepage in English” and when I translate it, I get only one version of the homepage in English, even if I switch to French, like if there were only one language possible at the same time for the homepage.
Can you help ?
many thanks : www.thegood.consulting
Julien

**Comment by mahendrapratap4022** [comment]
Hi, @Juliengoodconsulting can you share some more details like which plugin you are using I just have tested with the Polylang plugin and it is working like a charm. If you can let me know the plugin you use I can help in more detail.

**Comment by Juliengoodconsulting** [comment]
Hi, thanks for your kind reply :)
I am using Polylang 3.1.1.
When I duplicate my homepage and edit the new version, the modification (transmlation) i am making into the "shapely parallax" blocks apply on both versions, more precisely, it is like there were only one version of the homepage. It works prerfectly on all the other pages.
thanks again,
JL

**Comment by mahendrapratap4022** [comment]
Hi @Juliengoodconsulting I have tried one more time and it is working fine with no issue and bug. Here are some points you need to be sure about the plugin.

- Make sure you are selecting the right lang for the right page I have attached one screenshot which I have taken from eng page you can see.
- Check what page are you editing with the selected lang.
- Follow this video - https://www.youtube.com/watch?v=YpFdmzWCFRc&ab_channel=WordPressTutorials-WPLearningLab

<img width="462" alt="Screenshot 2021-09-03 at 3 58 27 PM" src="https://user-images.githubusercontent.com/33213474/131991273-19dc838f-4a5d-4242-a5ca-af723b3b763e.png">


If this does not fix your problem then please create one video of the issue.

**Comment by Juliengoodconsulting** [comment]
Hi, thanks a lot for your message.
As requested, please find a video of what I am facing. I hope it will be clear.
https://vimeo.com/606471755/d349a609fa

Thanks again,
Julien

**Comment by mahendrapratap4022** [comment]
Hi @Juliengoodconsulting 
Thanks for explaining it to me like this it is much clear now.
The actual issue is with the widget, WordPress widget supports one-time content for it so it can't change for other pages (including other lang pages) so in that case, I have one solution for you.
There is a plugin you can install call [widget-options](https://wordpress.org/plugins/widget-options/) please install it you will get the option to change the language in the widget I'm attaching a video that I have tested it will be helpful for you.

https://drive.google.com/file/d/1l3elfJBnUce3iPMGo-2MqPL_JHGLsxjD/view?usp=sharing

Thanks and let me know if you need more info (and mention me in the comment so it can be reached quickly to me 😉).
